frontend/config/routes.rb
Rails.application.routes.draw do
  get 'delete/show/:id', to:'delete#show', as: 'delete'
  resources :laborsocial
  

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root :to => 'laborsocial#index'
end

frontend/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

frontend/app/models/laborsocial.rb
class Laborsocial < ApplicationRecord
end

frontend/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

frontend/app/controllers/delete_controller.rb
require 'httparty'
class DeleteController < ApplicationController
  include HTTParty

  def show
    HTTParty.delete "http://localhost:8000/api/laborsocial/" + params.require(:id)
    
    respond_to do |format|
      format.html{redirect_to laborsocial_index_path, notice: 'Se ha eliminado correctamente el registro.'}
    end
  end
end

frontend/app/controllers/laborsocial_controller.rb
require 'httparty'
class LaborsocialController < ApplicationController
    include HTTParty
  
    def index
        @datos = HTTParty.get "http://localhost:8000/api/laborsocial"
    end

    def show
        @datos = HTTParty.get "http://localhost:8000/api/laborsocial/" + params.require(:id)
    end

    def new
        
    end

    def create
        
    end

    def edit
        @datos = HTTParty.get "http://localhost:8000/api/laborsocial/" + params.require(:id)
    end

    def redirect_cancel
        redirect_to laborsocial_index_path if params[:cancel]
    end

end

frontend/app/helpers/application_helper.rb
module ApplicationHelper
end

frontend/app/helpers/delete_helper.rb
module DeleteHelper
end

frontend/app/helpers/laborsocial_helper.rb
module LaborsocialHelper
end

frontend/app/helpers/principal_helper.rb
module PrincipalHelper
end

frontend/app/views/delete/show.html.erb
<h1>Delete</h1>
<p>Se ha eliminado el registro de forma correcta</p>
<%=link_to 'Back', laborsocial_index_path %>

frontend/app/views/laborsocial/edit.html.erb
<!DOCTYPE html>
<head>
    <style>
        h1{
            text-align: center;
        }

        *{box-sizing:border-box;}

        form{
            width:500px;
            padding:16px;
            border-radius:10px;
            margin:auto;
            background-color:#ccc;
        }

        form label{
            width:100px;
            font-weight:bold;
            display:inline-block;
        }

        form input[type="text"],
        form input[type="email"]{
            width:350px;
            padding:3px 10px;
            border:1px solid #f6f6f6;
            border-radius:3px;
            background-color:#f6f6f6;
            margin:8px 0;
            display:inline-block;
        }

        form input[type="submit"]{
            width:100%;
            padding:8px 16px;
            margin-top:32px;
            border:1px solid #000;
            border-radius:5px;
            display:block;
            color:#fff;
            background-color:#000;
        } 

        form input[type="submit"]:hover{
            cursor:pointer;
        }

        textarea{
            width:100%;
            height:100px;
            border:1px solid #f6f6f6;
            border-radius:3px;
            background-color:#f6f6f6;			
            margin:8px 0;
            resize:none;
            display:block;
        }
    </style>
</head>
<h1>Editar labor social</h1>
<%= form_with(url: "http://localhost:8000/api/laborsocial/" + params.require(:id), method: "put", local: false) do |f| %>
    <div>
        <%= f.label :nombres %>
        <%= f.text_field :nombres, :value => @datos["nombres"] %>
    </div>
    <div>
        <%= f.label :categoria %>
        <%= f.text_field :categoria, :value => @datos["categoria"] %>
    </div>
    <div>
        <%= f.label :finicial, "Fecha Inicial " %>
        <%= f.date_field :finicial, :value => @datos["finicial"] %>
    </div>
    <div>
        <%= f.label :ffinal, "Fecha Final " %>
        <%= f.date_field :ffinal, :value => @datos["ffinal"] %>
    </div>
    <div>
        <%= f.label :perfil %>
        <%= f.text_field :perfil, :value => @datos["perfil"] %>
    </div>
    <div>
        <%= f.label :descripcion %>
        <%= f.text_field :descripcion, :value => @datos["descripcion"] %>
    </div>
    <div>
        <%= f.label :competencias %>
        <%= f.text_field :competencias, :value => @datos["competencias"] %>
    </div>
    <div>
        <%= f.label :oferta %>
        <%= f.text_field :oferta, :value => @datos["oferta"] %>
    </div>

    <div>
        <%= f.submit :submit, :onclick => "regresar();" %>
    </div>

    <script type="text/javascript">
        function regresar() {
            location.href = "http://localhost:3000";
            console.log("Hola mundo");
        };
    </script>

<% end %>
<%= link_to 'Back', laborsocial_index_path %>

frontend/app/views/laborsocial/index.html.erb
<!DOCTYPE html>
<head>
    <style>
        a{
            font-size: 25px;
            font-style: italic;
        }
        h1{
            text-align: center;
        }

        table {
        table-layout: fixed;
        width: 100%;
        border-collapse: collapse;
        border: 3px solid purple;
        }

        thead th:nth-child(1) {
        width: 20%;
        }

        thead th:nth-child(2) {
        width: 10%;
        }

        thead th:nth-child(3) {
        width: 35%;
        }

        thead th:nth-child(4) {
        width: 20%;
        }

        th, td {
        padding: 20px;
        }
    </style>
</head>
<p id="notice"><%= notice %></p>
<h1>LABOR SOCIAL</h1>
<table border CELLPADDING=10 CELLSPACING=0>
    <button><%=link_to 'Crear Labor Social', new_laborsocial_path %></button>
    <thead>
        <tr>
            <th>Nombres</th>
            <th>Categoria</th>
            <th>Perfil</th>
            <th colspan="3">Opciones</th>
        </tr>
    </thead>
    <tbody>
        <% @datos.each do |dato| %>
            <tr>
                <td><%= dato["nombres"] %></td>
                <td><%= dato["categoria"] %></td>
                <td><%= dato["perfil"] %></td>
                <td><%= link_to "Show", laborsocial_path(dato["id"]) %></td>
                <td><%= link_to "Delete", delete_path(dato["id"])%></td>
                <td><%= link_to "Update", edit_laborsocial_path(dato["id"]) %></td>
            </tr>
        <% end %>
    </tbody> 
</table>

frontend/app/views/laborsocial/new.html.erb
<h1>Registro de Laborsocial</h1>

<%= form_with(url: "http://localhost:8000/api/laborsocial", method: "post", local: false) do |f| %>
    <div>
        <%= f.label :nombres %>
        <%= f.text_field :nombres %>
    </div>
    <div>
        <%= f.label :categoria %>
        <%= f.text_field :categoria %>
    </div>
    <div>
        <%= f.label :finicial %>
        <%= f.date_field :finicial %>
    </div>
    <div>
        <%= f.label :ffinal %>
        <%= f.date_field :ffinal %>
    </div>
    <div>
        <%= f.label :perfil %>
        <%= f.text_field :perfil %>
    </div>
    <div>
        <%= f.label :descripcion %>
        <%= f.text_field :descripcion %>
    </div>
    <div>
        <%= f.label :competencias %>
        <%= f.text_field :competencias %>
    </div>
    <div>
        <%= f.label :oferta %>
        <%= f.text_field :oferta %>
    </div>

    <div>
        <%= f.submit %>
    </div>
<% end %>
<%= link_to 'Back', laborsocial_index_path %>

frontend/app/views/laborsocial/show.html.erb
<h1>Informacion completa de <%= @datos["nombres"] %></h1>
<head>
    <style>
        strong,a{
            font-size: 25px;
        }
        strong{
            padding-right: 10px;
        }
    </style>
</head>
<p>
    <strong>Nombres: </strong>
    <a><%= @datos["nombres"] %><a><br>

    <strong>Categoria: </strong>
    <%= @datos["categoria"] %><br>

    <strong>Fecha Inicial: </strong>
    <%= @datos["finicial"] %><br>

    <strong>Fecha Final: </strong>
    <%= @datos["ffinal"] %><br>

    <strong>Perfil: </strong>
    <%= @datos["perfil"] %><br>

    <strong>Descripcion: </strong>
    <%= @datos["descripcion"] %><br>

    <strong>Competencias: </strong>
    <%= @datos["competencias"] %><br>

    <strong>Oferta: </strong>
    <%= @datos["oferta"] %><br>
</p>

<%= link_to 'Back', laborsocial_index_path %> 

frontend/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Frontend</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

frontend/app/views/principal/index.html.erb
<h1>LABOR SOCIAL</h1>
<table border>
    <thead>
        <tr>
            <th>Nombres</th>
            <th>Categoria</th>
            <th>Perfil</th>
        </tr>
    </thead>
    <tbody>
        <% @datos.each do |dato| %>
            <tr>
                <td><%= dato["nombres"] %></td>
                <td><%= dato["categoria"] %></td>
                <td><%= dato["perfil"] %></td>
            </tr>
        <% end %>
    </tbody>

</table>